// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/BaseKVStoreService.proto

package com.zachary.bifromq.basekv.store.proto;

/**
 * Protobuf type {@code basekv.ChangeReplicaConfigRequest}
 */
public final class ChangeReplicaConfigRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basekv.ChangeReplicaConfigRequest)
    ChangeReplicaConfigRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChangeReplicaConfigRequest.newBuilder() to construct.
  private ChangeReplicaConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChangeReplicaConfigRequest() {
    newVoters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    newLearners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChangeReplicaConfigRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.basekv.store.proto.BaseKVStoreServiceOuterClass.internal_static_basekv_ChangeReplicaConfigRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.basekv.store.proto.BaseKVStoreServiceOuterClass.internal_static_basekv_ChangeReplicaConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.class, com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private long reqId_ = 0L;
  /**
   * <code>uint64 reqId = 1;</code>
   * @return The reqId.
   */
  @java.lang.Override
  public long getReqId() {
    return reqId_;
  }

  public static final int VER_FIELD_NUMBER = 2;
  private long ver_ = 0L;
  /**
   * <code>uint64 ver = 2;</code>
   * @return The ver.
   */
  @java.lang.Override
  public long getVer() {
    return ver_;
  }

  public static final int KVRANGEID_FIELD_NUMBER = 3;
  private com.zachary.bifromq.basekv.proto.KVRangeId kvRangeId_;
  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   * @return Whether the kvRangeId field is set.
   */
  @java.lang.Override
  public boolean hasKvRangeId() {
    return kvRangeId_ != null;
  }
  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   * @return The kvRangeId.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeId getKvRangeId() {
    return kvRangeId_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : kvRangeId_;
  }
  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getKvRangeIdOrBuilder() {
    return kvRangeId_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : kvRangeId_;
  }

  public static final int NEWVOTERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList newVoters_;
  /**
   * <code>repeated string newVoters = 4;</code>
   * @return A list containing the newVoters.
   */
  public com.google.protobuf.ProtocolStringList
      getNewVotersList() {
    return newVoters_;
  }
  /**
   * <code>repeated string newVoters = 4;</code>
   * @return The count of newVoters.
   */
  public int getNewVotersCount() {
    return newVoters_.size();
  }
  /**
   * <code>repeated string newVoters = 4;</code>
   * @param index The index of the element to return.
   * @return The newVoters at the given index.
   */
  public java.lang.String getNewVoters(int index) {
    return newVoters_.get(index);
  }
  /**
   * <code>repeated string newVoters = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the newVoters at the given index.
   */
  public com.google.protobuf.ByteString
      getNewVotersBytes(int index) {
    return newVoters_.getByteString(index);
  }

  public static final int NEWLEARNERS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList newLearners_;
  /**
   * <code>repeated string newLearners = 5;</code>
   * @return A list containing the newLearners.
   */
  public com.google.protobuf.ProtocolStringList
      getNewLearnersList() {
    return newLearners_;
  }
  /**
   * <code>repeated string newLearners = 5;</code>
   * @return The count of newLearners.
   */
  public int getNewLearnersCount() {
    return newLearners_.size();
  }
  /**
   * <code>repeated string newLearners = 5;</code>
   * @param index The index of the element to return.
   * @return The newLearners at the given index.
   */
  public java.lang.String getNewLearners(int index) {
    return newLearners_.get(index);
  }
  /**
   * <code>repeated string newLearners = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the newLearners at the given index.
   */
  public com.google.protobuf.ByteString
      getNewLearnersBytes(int index) {
    return newLearners_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reqId_ != 0L) {
      output.writeUInt64(1, reqId_);
    }
    if (ver_ != 0L) {
      output.writeUInt64(2, ver_);
    }
    if (kvRangeId_ != null) {
      output.writeMessage(3, getKvRangeId());
    }
    for (int i = 0; i < newVoters_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, newVoters_.getRaw(i));
    }
    for (int i = 0; i < newLearners_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, newLearners_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, reqId_);
    }
    if (ver_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ver_);
    }
    if (kvRangeId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getKvRangeId());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < newVoters_.size(); i++) {
        dataSize += computeStringSizeNoTag(newVoters_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNewVotersList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < newLearners_.size(); i++) {
        dataSize += computeStringSizeNoTag(newLearners_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNewLearnersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest other = (com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest) obj;

    if (getReqId()
        != other.getReqId()) return false;
    if (getVer()
        != other.getVer()) return false;
    if (hasKvRangeId() != other.hasKvRangeId()) return false;
    if (hasKvRangeId()) {
      if (!getKvRangeId()
          .equals(other.getKvRangeId())) return false;
    }
    if (!getNewVotersList()
        .equals(other.getNewVotersList())) return false;
    if (!getNewLearnersList()
        .equals(other.getNewLearnersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReqId());
    hash = (37 * hash) + VER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVer());
    if (hasKvRangeId()) {
      hash = (37 * hash) + KVRANGEID_FIELD_NUMBER;
      hash = (53 * hash) + getKvRangeId().hashCode();
    }
    if (getNewVotersCount() > 0) {
      hash = (37 * hash) + NEWVOTERS_FIELD_NUMBER;
      hash = (53 * hash) + getNewVotersList().hashCode();
    }
    if (getNewLearnersCount() > 0) {
      hash = (37 * hash) + NEWLEARNERS_FIELD_NUMBER;
      hash = (53 * hash) + getNewLearnersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code basekv.ChangeReplicaConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basekv.ChangeReplicaConfigRequest)
      com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.basekv.store.proto.BaseKVStoreServiceOuterClass.internal_static_basekv_ChangeReplicaConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.basekv.store.proto.BaseKVStoreServiceOuterClass.internal_static_basekv_ChangeReplicaConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.class, com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.Builder.class);
    }

    // Construct using com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reqId_ = 0L;
      ver_ = 0L;
      kvRangeId_ = null;
      if (kvRangeIdBuilder_ != null) {
        kvRangeIdBuilder_.dispose();
        kvRangeIdBuilder_ = null;
      }
      newVoters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      newLearners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.basekv.store.proto.BaseKVStoreServiceOuterClass.internal_static_basekv_ChangeReplicaConfigRequest_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest getDefaultInstanceForType() {
      return com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest build() {
      com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest buildPartial() {
      com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest result = new com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest result) {
      if (((bitField0_ & 0x00000008) != 0)) {
        newVoters_ = newVoters_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.newVoters_ = newVoters_;
      if (((bitField0_ & 0x00000010) != 0)) {
        newLearners_ = newLearners_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.newLearners_ = newLearners_;
    }

    private void buildPartial0(com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reqId_ = reqId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ver_ = ver_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.kvRangeId_ = kvRangeIdBuilder_ == null
            ? kvRangeId_
            : kvRangeIdBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest) {
        return mergeFrom((com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest other) {
      if (other == com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest.getDefaultInstance()) return this;
      if (other.getReqId() != 0L) {
        setReqId(other.getReqId());
      }
      if (other.getVer() != 0L) {
        setVer(other.getVer());
      }
      if (other.hasKvRangeId()) {
        mergeKvRangeId(other.getKvRangeId());
      }
      if (!other.newVoters_.isEmpty()) {
        if (newVoters_.isEmpty()) {
          newVoters_ = other.newVoters_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureNewVotersIsMutable();
          newVoters_.addAll(other.newVoters_);
        }
        onChanged();
      }
      if (!other.newLearners_.isEmpty()) {
        if (newLearners_.isEmpty()) {
          newLearners_ = other.newLearners_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureNewLearnersIsMutable();
          newLearners_.addAll(other.newLearners_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              reqId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              ver_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getKvRangeIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNewVotersIsMutable();
              newVoters_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNewLearnersIsMutable();
              newLearners_.add(s);
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long reqId_ ;
    /**
     * <code>uint64 reqId = 1;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public long getReqId() {
      return reqId_;
    }
    /**
     * <code>uint64 reqId = 1;</code>
     * @param value The reqId to set.
     * @return This builder for chaining.
     */
    public Builder setReqId(long value) {
      
      reqId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 reqId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReqId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reqId_ = 0L;
      onChanged();
      return this;
    }

    private long ver_ ;
    /**
     * <code>uint64 ver = 2;</code>
     * @return The ver.
     */
    @java.lang.Override
    public long getVer() {
      return ver_;
    }
    /**
     * <code>uint64 ver = 2;</code>
     * @param value The ver to set.
     * @return This builder for chaining.
     */
    public Builder setVer(long value) {
      
      ver_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ver = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVer() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ver_ = 0L;
      onChanged();
      return this;
    }

    private com.zachary.bifromq.basekv.proto.KVRangeId kvRangeId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder> kvRangeIdBuilder_;
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     * @return Whether the kvRangeId field is set.
     */
    public boolean hasKvRangeId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     * @return The kvRangeId.
     */
    public com.zachary.bifromq.basekv.proto.KVRangeId getKvRangeId() {
      if (kvRangeIdBuilder_ == null) {
        return kvRangeId_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : kvRangeId_;
      } else {
        return kvRangeIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public Builder setKvRangeId(com.zachary.bifromq.basekv.proto.KVRangeId value) {
      if (kvRangeIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kvRangeId_ = value;
      } else {
        kvRangeIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public Builder setKvRangeId(
        com.zachary.bifromq.basekv.proto.KVRangeId.Builder builderForValue) {
      if (kvRangeIdBuilder_ == null) {
        kvRangeId_ = builderForValue.build();
      } else {
        kvRangeIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public Builder mergeKvRangeId(com.zachary.bifromq.basekv.proto.KVRangeId value) {
      if (kvRangeIdBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          kvRangeId_ != null &&
          kvRangeId_ != com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance()) {
          getKvRangeIdBuilder().mergeFrom(value);
        } else {
          kvRangeId_ = value;
        }
      } else {
        kvRangeIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public Builder clearKvRangeId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      kvRangeId_ = null;
      if (kvRangeIdBuilder_ != null) {
        kvRangeIdBuilder_.dispose();
        kvRangeIdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeId.Builder getKvRangeIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getKvRangeIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getKvRangeIdOrBuilder() {
      if (kvRangeIdBuilder_ != null) {
        return kvRangeIdBuilder_.getMessageOrBuilder();
      } else {
        return kvRangeId_ == null ?
            com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : kvRangeId_;
      }
    }
    /**
     * <code>.basekv.KVRangeId kvRangeId = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder> 
        getKvRangeIdFieldBuilder() {
      if (kvRangeIdBuilder_ == null) {
        kvRangeIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder>(
                getKvRangeId(),
                getParentForChildren(),
                isClean());
        kvRangeId_ = null;
      }
      return kvRangeIdBuilder_;
    }

    private com.google.protobuf.LazyStringList newVoters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNewVotersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        newVoters_ = new com.google.protobuf.LazyStringArrayList(newVoters_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @return A list containing the newVoters.
     */
    public com.google.protobuf.ProtocolStringList
        getNewVotersList() {
      return newVoters_.getUnmodifiableView();
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @return The count of newVoters.
     */
    public int getNewVotersCount() {
      return newVoters_.size();
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param index The index of the element to return.
     * @return The newVoters at the given index.
     */
    public java.lang.String getNewVoters(int index) {
      return newVoters_.get(index);
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the newVoters at the given index.
     */
    public com.google.protobuf.ByteString
        getNewVotersBytes(int index) {
      return newVoters_.getByteString(index);
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param index The index to set the value at.
     * @param value The newVoters to set.
     * @return This builder for chaining.
     */
    public Builder setNewVoters(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNewVotersIsMutable();
      newVoters_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param value The newVoters to add.
     * @return This builder for chaining.
     */
    public Builder addNewVoters(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNewVotersIsMutable();
      newVoters_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param values The newVoters to add.
     * @return This builder for chaining.
     */
    public Builder addAllNewVoters(
        java.lang.Iterable<java.lang.String> values) {
      ensureNewVotersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, newVoters_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewVoters() {
      newVoters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newVoters = 4;</code>
     * @param value The bytes of the newVoters to add.
     * @return This builder for chaining.
     */
    public Builder addNewVotersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNewVotersIsMutable();
      newVoters_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList newLearners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNewLearnersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        newLearners_ = new com.google.protobuf.LazyStringArrayList(newLearners_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @return A list containing the newLearners.
     */
    public com.google.protobuf.ProtocolStringList
        getNewLearnersList() {
      return newLearners_.getUnmodifiableView();
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @return The count of newLearners.
     */
    public int getNewLearnersCount() {
      return newLearners_.size();
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param index The index of the element to return.
     * @return The newLearners at the given index.
     */
    public java.lang.String getNewLearners(int index) {
      return newLearners_.get(index);
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the newLearners at the given index.
     */
    public com.google.protobuf.ByteString
        getNewLearnersBytes(int index) {
      return newLearners_.getByteString(index);
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param index The index to set the value at.
     * @param value The newLearners to set.
     * @return This builder for chaining.
     */
    public Builder setNewLearners(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNewLearnersIsMutable();
      newLearners_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param value The newLearners to add.
     * @return This builder for chaining.
     */
    public Builder addNewLearners(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNewLearnersIsMutable();
      newLearners_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param values The newLearners to add.
     * @return This builder for chaining.
     */
    public Builder addAllNewLearners(
        java.lang.Iterable<java.lang.String> values) {
      ensureNewLearnersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, newLearners_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewLearners() {
      newLearners_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string newLearners = 5;</code>
     * @param value The bytes of the newLearners to add.
     * @return This builder for chaining.
     */
    public Builder addNewLearnersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNewLearnersIsMutable();
      newLearners_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basekv.ChangeReplicaConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:basekv.ChangeReplicaConfigRequest)
  private static final com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest();
  }

  public static com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeReplicaConfigRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChangeReplicaConfigRequest>() {
    @java.lang.Override
    public ChangeReplicaConfigRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChangeReplicaConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeReplicaConfigRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.basekv.store.proto.ChangeReplicaConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

