// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/BaseKVStoreService.proto

package com.zachary.bifromq.basekv.store.proto;

public interface KVRangeMergeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.KVRangeMergeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>uint64 ver = 2;</code>
   * @return The ver.
   */
  long getVer();

  /**
   * <code>.basekv.KVRangeId mergerId = 3;</code>
   * @return Whether the mergerId field is set.
   */
  boolean hasMergerId();
  /**
   * <code>.basekv.KVRangeId mergerId = 3;</code>
   * @return The mergerId.
   */
  com.zachary.bifromq.basekv.proto.KVRangeId getMergerId();
  /**
   * <code>.basekv.KVRangeId mergerId = 3;</code>
   */
  com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getMergerIdOrBuilder();

  /**
   * <code>.basekv.KVRangeId mergeeId = 4;</code>
   * @return Whether the mergeeId field is set.
   */
  boolean hasMergeeId();
  /**
   * <code>.basekv.KVRangeId mergeeId = 4;</code>
   * @return The mergeeId.
   */
  com.zachary.bifromq.basekv.proto.KVRangeId getMergeeId();
  /**
   * <code>.basekv.KVRangeId mergeeId = 4;</code>
   */
  com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getMergeeIdOrBuilder();
}
