// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/BaseKVStoreService.proto

package com.zachary.bifromq.basekv.store.proto;

public interface KVRangeRORequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.KVRangeRORequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>uint64 ver = 2;</code>
   * @return The ver.
   */
  long getVer();

  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   * @return Whether the kvRangeId field is set.
   */
  boolean hasKvRangeId();
  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   * @return The kvRangeId.
   */
  com.zachary.bifromq.basekv.proto.KVRangeId getKvRangeId();
  /**
   * <code>.basekv.KVRangeId kvRangeId = 3;</code>
   */
  com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getKvRangeIdOrBuilder();

  /**
   * <code>bytes existKey = 4;</code>
   * @return Whether the existKey field is set.
   */
  boolean hasExistKey();
  /**
   * <code>bytes existKey = 4;</code>
   * @return The existKey.
   */
  com.google.protobuf.ByteString getExistKey();

  /**
   * <code>bytes getKey = 5;</code>
   * @return Whether the getKey field is set.
   */
  boolean hasGetKey();
  /**
   * <code>bytes getKey = 5;</code>
   * @return The getKey.
   */
  com.google.protobuf.ByteString getGetKey();

  /**
   * <code>bytes roCoProcInput = 6;</code>
   * @return Whether the roCoProcInput field is set.
   */
  boolean hasRoCoProcInput();
  /**
   * <code>bytes roCoProcInput = 6;</code>
   * @return The roCoProcInput.
   */
  com.google.protobuf.ByteString getRoCoProcInput();

  public com.zachary.bifromq.basekv.store.proto.KVRangeRORequest.TypeCase getTypeCase();
}
