// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: retainservice/RetainCoProc.proto

package com.zachary.bifromq.retain.rpc.proto;

/**
 * Protobuf type {@code retainservice.RetainServiceROCoProcInput}
 */
public final class RetainServiceROCoProcInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:retainservice.RetainServiceROCoProcInput)
    RetainServiceROCoProcInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetainServiceROCoProcInput.newBuilder() to construct.
  private RetainServiceROCoProcInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetainServiceROCoProcInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RetainServiceROCoProcInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.retain.rpc.proto.RetainCoProcProtos.internal_static_retainservice_RetainServiceROCoProcInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.retain.rpc.proto.RetainCoProcProtos.internal_static_retainservice_RetainServiceROCoProcInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.class, com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.Builder.class);
  }

  private int typeCase_ = 0;
  private java.lang.Object type_;
  public enum TypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MATCHREQUEST(1),
    TYPE_NOT_SET(0);
    private final int value;
    private TypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TypeCase forNumber(int value) {
      switch (value) {
        case 1: return MATCHREQUEST;
        case 0: return TYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TypeCase
  getTypeCase() {
    return TypeCase.forNumber(
        typeCase_);
  }

  public static final int MATCHREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
   * @return Whether the matchRequest field is set.
   */
  @java.lang.Override
  public boolean hasMatchRequest() {
    return typeCase_ == 1;
  }
  /**
   * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
   * @return The matchRequest.
   */
  @java.lang.Override
  public com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest getMatchRequest() {
    if (typeCase_ == 1) {
       return (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_;
    }
    return com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
  }
  /**
   * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequestOrBuilder getMatchRequestOrBuilder() {
    if (typeCase_ == 1) {
       return (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_;
    }
    return com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (typeCase_ == 1) {
      output.writeMessage(1, (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput other = (com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput) obj;

    if (!getTypeCase().equals(other.getTypeCase())) return false;
    switch (typeCase_) {
      case 1:
        if (!getMatchRequest()
            .equals(other.getMatchRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (typeCase_) {
      case 1:
        hash = (37 * hash) + MATCHREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getMatchRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code retainservice.RetainServiceROCoProcInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:retainservice.RetainServiceROCoProcInput)
      com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.retain.rpc.proto.RetainCoProcProtos.internal_static_retainservice_RetainServiceROCoProcInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.retain.rpc.proto.RetainCoProcProtos.internal_static_retainservice_RetainServiceROCoProcInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.class, com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.Builder.class);
    }

    // Construct using com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (matchRequestBuilder_ != null) {
        matchRequestBuilder_.clear();
      }
      typeCase_ = 0;
      type_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.retain.rpc.proto.RetainCoProcProtos.internal_static_retainservice_RetainServiceROCoProcInput_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput getDefaultInstanceForType() {
      return com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput build() {
      com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput buildPartial() {
      com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput result = new com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput result) {
      result.typeCase_ = typeCase_;
      result.type_ = this.type_;
      if (typeCase_ == 1 &&
          matchRequestBuilder_ != null) {
        result.type_ = matchRequestBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput) {
        return mergeFrom((com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput other) {
      if (other == com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput.getDefaultInstance()) return this;
      switch (other.getTypeCase()) {
        case MATCHREQUEST: {
          mergeMatchRequest(other.getMatchRequest());
          break;
        }
        case TYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMatchRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              typeCase_ = 1;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int typeCase_ = 0;
    private java.lang.Object type_;
    public TypeCase
        getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public Builder clearType() {
      typeCase_ = 0;
      type_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.Builder, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequestOrBuilder> matchRequestBuilder_;
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     * @return Whether the matchRequest field is set.
     */
    @java.lang.Override
    public boolean hasMatchRequest() {
      return typeCase_ == 1;
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     * @return The matchRequest.
     */
    @java.lang.Override
    public com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest getMatchRequest() {
      if (matchRequestBuilder_ == null) {
        if (typeCase_ == 1) {
          return (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_;
        }
        return com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
      } else {
        if (typeCase_ == 1) {
          return matchRequestBuilder_.getMessage();
        }
        return com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    public Builder setMatchRequest(com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest value) {
      if (matchRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        matchRequestBuilder_.setMessage(value);
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    public Builder setMatchRequest(
        com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.Builder builderForValue) {
      if (matchRequestBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        matchRequestBuilder_.setMessage(builderForValue.build());
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    public Builder mergeMatchRequest(com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest value) {
      if (matchRequestBuilder_ == null) {
        if (typeCase_ == 1 &&
            type_ != com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance()) {
          type_ = com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.newBuilder((com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_)
              .mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        if (typeCase_ == 1) {
          matchRequestBuilder_.mergeFrom(value);
        } else {
          matchRequestBuilder_.setMessage(value);
        }
      }
      typeCase_ = 1;
      return this;
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    public Builder clearMatchRequest() {
      if (matchRequestBuilder_ == null) {
        if (typeCase_ == 1) {
          typeCase_ = 0;
          type_ = null;
          onChanged();
        }
      } else {
        if (typeCase_ == 1) {
          typeCase_ = 0;
          type_ = null;
        }
        matchRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    public com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.Builder getMatchRequestBuilder() {
      return getMatchRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    @java.lang.Override
    public com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequestOrBuilder getMatchRequestOrBuilder() {
      if ((typeCase_ == 1) && (matchRequestBuilder_ != null)) {
        return matchRequestBuilder_.getMessageOrBuilder();
      } else {
        if (typeCase_ == 1) {
          return (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_;
        }
        return com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.retainservice.MatchCoProcRequest matchRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.Builder, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequestOrBuilder> 
        getMatchRequestFieldBuilder() {
      if (matchRequestBuilder_ == null) {
        if (!(typeCase_ == 1)) {
          type_ = com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.getDefaultInstance();
        }
        matchRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest.Builder, com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequestOrBuilder>(
                (com.zachary.bifromq.retain.rpc.proto.MatchCoProcRequest) type_,
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      typeCase_ = 1;
      onChanged();
      return matchRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:retainservice.RetainServiceROCoProcInput)
  }

  // @@protoc_insertion_point(class_scope:retainservice.RetainServiceROCoProcInput)
  private static final com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput();
  }

  public static com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetainServiceROCoProcInput>
      PARSER = new com.google.protobuf.AbstractParser<RetainServiceROCoProcInput>() {
    @java.lang.Override
    public RetainServiceROCoProcInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RetainServiceROCoProcInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetainServiceROCoProcInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.retain.rpc.proto.RetainServiceROCoProcInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

