// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mqttbroker/MessageReceiver.proto

package com.zachary.bifromq.mqtt.inbox.rpc.proto;

public final class MessageReceiverProtos {
  private MessageReceiverProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_DeliveryPack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_DeliveryPack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_WriteResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_WriteResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_WriteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_WriteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_HasInboxRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_HasInboxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mqttbroker_HasInboxReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mqttbroker_HasInboxReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n mqttbroker/MessageReceiver.proto\022\nmqtt" +
      "broker\032\030commontype/SubInfo.proto\032\035common" +
      "type/TopicMessage.proto\"j\n\014DeliveryPack\022" +
      "1\n\013messagePack\030\001 \001(\0132\034.commontype.TopicM" +
      "essagePack\022\'\n\nsubscriber\030\002 \003(\0132\023.commont" +
      "ype.SubInfo\"M\n\014WriteRequest\022\r\n\005reqId\030\001 \001" +
      "(\004\022.\n\014deliveryPack\030\002 \003(\0132\030.mqttbroker.De" +
      "liveryPack\"\203\001\n\013WriteResult\022$\n\007subInfo\030\001 " +
      "\001(\0132\023.commontype.SubInfo\022.\n\006result\030\002 \001(\016" +
      "2\036.mqttbroker.WriteResult.Result\"\036\n\006Resu" +
      "lt\022\006\n\002OK\020\000\022\014\n\010NO_INBOX\020\001\"D\n\nWriteReply\022\r" +
      "\n\005reqId\030\001 \001(\004\022\'\n\006result\030\002 \003(\0132\027.mqttbrok" +
      "er.WriteResult\"1\n\017HasInboxRequest\022\r\n\005req" +
      "Id\030\001 \001(\004\022\017\n\007inboxId\030\002 \001(\t\".\n\rHasInboxRep" +
      "ly\022\r\n\005reqId\030\001 \001(\004\022\016\n\006result\030\002 \001(\0102\226\001\n\021On" +
      "lineInboxBroker\022=\n\005write\022\030.mqttbroker.Wr" +
      "iteRequest\032\026.mqttbroker.WriteReply(\0010\001\022B" +
      "\n\010hasInbox\022\033.mqttbroker.HasInboxRequest\032" +
      "\031.mqttbroker.HasInboxReplyBC\n(com.zachar" +
      "y.bifromq.mqtt.inbox.rpc.protoB\025MessageR" +
      "eceiverProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zachary.bifromq.type.SubInfoProtos.getDescriptor(),
          com.zachary.bifromq.type.TopicMessageProtos.getDescriptor(),
        });
    internal_static_mqttbroker_DeliveryPack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mqttbroker_DeliveryPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_DeliveryPack_descriptor,
        new java.lang.String[] { "MessagePack", "Subscriber", });
    internal_static_mqttbroker_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mqttbroker_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_WriteRequest_descriptor,
        new java.lang.String[] { "ReqId", "DeliveryPack", });
    internal_static_mqttbroker_WriteResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mqttbroker_WriteResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_WriteResult_descriptor,
        new java.lang.String[] { "SubInfo", "Result", });
    internal_static_mqttbroker_WriteReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mqttbroker_WriteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_WriteReply_descriptor,
        new java.lang.String[] { "ReqId", "Result", });
    internal_static_mqttbroker_HasInboxRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mqttbroker_HasInboxRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_HasInboxRequest_descriptor,
        new java.lang.String[] { "ReqId", "InboxId", });
    internal_static_mqttbroker_HasInboxReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mqttbroker_HasInboxReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mqttbroker_HasInboxReply_descriptor,
        new java.lang.String[] { "ReqId", "Result", });
    com.zachary.bifromq.type.SubInfoProtos.getDescriptor();
    com.zachary.bifromq.type.TopicMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
