// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxservice/InboxCoProc.proto

package com.zachary.bifromq.inbox.storage.proto;

public interface GCReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inboxservice.GCReply)
    com.google.protobuf.MessageOrBuilder {
}
