// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxservice/InboxCoProc.proto

package com.zachary.bifromq.inbox.storage.proto;

public interface InboxFetchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inboxservice.InboxFetchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * key: scopedInboxIdUtf8
   * </pre>
   *
   * <code>map&lt;string, .inboxservice.FetchParams&gt; inboxFetch = 1;</code>
   */
  int getInboxFetchCount();
  /**
   * <pre>
   * key: scopedInboxIdUtf8
   * </pre>
   *
   * <code>map&lt;string, .inboxservice.FetchParams&gt; inboxFetch = 1;</code>
   */
  boolean containsInboxFetch(
      java.lang.String key);
  /**
   * Use {@link #getInboxFetchMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.zachary.bifromq.inbox.storage.proto.FetchParams>
  getInboxFetch();
  /**
   * <pre>
   * key: scopedInboxIdUtf8
   * </pre>
   *
   * <code>map&lt;string, .inboxservice.FetchParams&gt; inboxFetch = 1;</code>
   */
  java.util.Map<java.lang.String, com.zachary.bifromq.inbox.storage.proto.FetchParams>
  getInboxFetchMap();
  /**
   * <pre>
   * key: scopedInboxIdUtf8
   * </pre>
   *
   * <code>map&lt;string, .inboxservice.FetchParams&gt; inboxFetch = 1;</code>
   */
  /* nullable */
com.zachary.bifromq.inbox.storage.proto.FetchParams getInboxFetchOrDefault(
      java.lang.String key,
      /* nullable */
com.zachary.bifromq.inbox.storage.proto.FetchParams defaultValue);
  /**
   * <pre>
   * key: scopedInboxIdUtf8
   * </pre>
   *
   * <code>map&lt;string, .inboxservice.FetchParams&gt; inboxFetch = 1;</code>
   */
  com.zachary.bifromq.inbox.storage.proto.FetchParams getInboxFetchOrThrow(
      java.lang.String key);
}
