// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecluster/messenger/MessengerMessage.proto

package com.zachary.bifromq.basecluster.messenger.proto;

public interface DirectMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basecluster.messenger.DirectMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes payload = 1;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
