// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecluster/fd/Ack.proto

package com.zachary.bifromq.basecluster.fd.proto;

public final class AckProtos {
  private AckProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_basecluster_fd_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_basecluster_fd_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030basecluster/fd/Ack.proto\022\016basecluster." +
      "fd\"\024\n\003Ack\022\r\n\005seqNo\030\001 \001(\rB9\n(com.zachary." +
      "bifromq.basecluster.fd.protoB\tAckProtosH" +
      "\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_basecluster_fd_Ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_basecluster_fd_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_basecluster_fd_Ack_descriptor,
        new java.lang.String[] { "SeqNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
