// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecluster/fd/Ping.proto

package com.zachary.bifromq.basecluster.fd.proto;

/**
 * <pre>
 **
 *用于发起 集群节点之间的 Ping 请求
 * </pre>
 *
 * Protobuf type {@code basecluster.fd.Ping}
 */
public final class Ping extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basecluster.fd.Ping)
    PingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ping.newBuilder() to construct.
  private Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ping() {
    id_ = com.google.protobuf.ByteString.EMPTY;
    pingerId_ = com.google.protobuf.ByteString.EMPTY;
    pingerAddr_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ping();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.basecluster.fd.proto.PingProtos.internal_static_basecluster_fd_Ping_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.basecluster.fd.proto.PingProtos.internal_static_basecluster_fd_Ping_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.basecluster.fd.proto.Ping.class, com.zachary.bifromq.basecluster.fd.proto.Ping.Builder.class);
  }

  public static final int SEQNO_FIELD_NUMBER = 1;
  private int seqNo_ = 0;
  /**
   * <pre>
   * seqNo used to track ack
   * </pre>
   *
   * <code>uint32 seqNo = 1;</code>
   * @return The seqNo.
   */
  @java.lang.Override
  public int getSeqNo() {
    return seqNo_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * name of the target member
   * </pre>
   *
   * <code>bytes id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getId() {
    return id_;
  }

  public static final int PINGERID_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString pingerId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * name of the pinger member
   * </pre>
   *
   * <code>bytes pingerId = 3;</code>
   * @return The pingerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPingerId() {
    return pingerId_;
  }

  public static final int PINGERADDR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pingerAddr_ = "";
  /**
   * <pre>
   * addr of the pinger member
   * </pre>
   *
   * <code>string pingerAddr = 4;</code>
   * @return The pingerAddr.
   */
  @java.lang.Override
  public java.lang.String getPingerAddr() {
    java.lang.Object ref = pingerAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pingerAddr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * addr of the pinger member
   * </pre>
   *
   * <code>string pingerAddr = 4;</code>
   * @return The bytes for pingerAddr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPingerAddrBytes() {
    java.lang.Object ref = pingerAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pingerAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PINGERPORT_FIELD_NUMBER = 5;
  private int pingerPort_ = 0;
  /**
   * <pre>
   * port to the pinger member
   * </pre>
   *
   * <code>uint32 pingerPort = 5;</code>
   * @return The pingerPort.
   */
  @java.lang.Override
  public int getPingerPort() {
    return pingerPort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seqNo_ != 0) {
      output.writeUInt32(1, seqNo_);
    }
    if (!id_.isEmpty()) {
      output.writeBytes(2, id_);
    }
    if (!pingerId_.isEmpty()) {
      output.writeBytes(3, pingerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pingerAddr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pingerAddr_);
    }
    if (pingerPort_ != 0) {
      output.writeUInt32(5, pingerPort_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seqNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, seqNo_);
    }
    if (!id_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, id_);
    }
    if (!pingerId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, pingerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pingerAddr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pingerAddr_);
    }
    if (pingerPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, pingerPort_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.basecluster.fd.proto.Ping)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.basecluster.fd.proto.Ping other = (com.zachary.bifromq.basecluster.fd.proto.Ping) obj;

    if (getSeqNo()
        != other.getSeqNo()) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (!getPingerId()
        .equals(other.getPingerId())) return false;
    if (!getPingerAddr()
        .equals(other.getPingerAddr())) return false;
    if (getPingerPort()
        != other.getPingerPort()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEQNO_FIELD_NUMBER;
    hash = (53 * hash) + getSeqNo();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PINGERID_FIELD_NUMBER;
    hash = (53 * hash) + getPingerId().hashCode();
    hash = (37 * hash) + PINGERADDR_FIELD_NUMBER;
    hash = (53 * hash) + getPingerAddr().hashCode();
    hash = (37 * hash) + PINGERPORT_FIELD_NUMBER;
    hash = (53 * hash) + getPingerPort();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basecluster.fd.proto.Ping parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.basecluster.fd.proto.Ping prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   *用于发起 集群节点之间的 Ping 请求
   * </pre>
   *
   * Protobuf type {@code basecluster.fd.Ping}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basecluster.fd.Ping)
      com.zachary.bifromq.basecluster.fd.proto.PingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.basecluster.fd.proto.PingProtos.internal_static_basecluster_fd_Ping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.basecluster.fd.proto.PingProtos.internal_static_basecluster_fd_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.basecluster.fd.proto.Ping.class, com.zachary.bifromq.basecluster.fd.proto.Ping.Builder.class);
    }

    // Construct using com.zachary.bifromq.basecluster.fd.proto.Ping.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      seqNo_ = 0;
      id_ = com.google.protobuf.ByteString.EMPTY;
      pingerId_ = com.google.protobuf.ByteString.EMPTY;
      pingerAddr_ = "";
      pingerPort_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.basecluster.fd.proto.PingProtos.internal_static_basecluster_fd_Ping_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.basecluster.fd.proto.Ping getDefaultInstanceForType() {
      return com.zachary.bifromq.basecluster.fd.proto.Ping.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.basecluster.fd.proto.Ping build() {
      com.zachary.bifromq.basecluster.fd.proto.Ping result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.basecluster.fd.proto.Ping buildPartial() {
      com.zachary.bifromq.basecluster.fd.proto.Ping result = new com.zachary.bifromq.basecluster.fd.proto.Ping(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.zachary.bifromq.basecluster.fd.proto.Ping result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.seqNo_ = seqNo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pingerId_ = pingerId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pingerAddr_ = pingerAddr_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pingerPort_ = pingerPort_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.basecluster.fd.proto.Ping) {
        return mergeFrom((com.zachary.bifromq.basecluster.fd.proto.Ping)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.basecluster.fd.proto.Ping other) {
      if (other == com.zachary.bifromq.basecluster.fd.proto.Ping.getDefaultInstance()) return this;
      if (other.getSeqNo() != 0) {
        setSeqNo(other.getSeqNo());
      }
      if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
        setId(other.getId());
      }
      if (other.getPingerId() != com.google.protobuf.ByteString.EMPTY) {
        setPingerId(other.getPingerId());
      }
      if (!other.getPingerAddr().isEmpty()) {
        pingerAddr_ = other.pingerAddr_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getPingerPort() != 0) {
        setPingerPort(other.getPingerPort());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              seqNo_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              id_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              pingerId_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              pingerAddr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              pingerPort_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int seqNo_ ;
    /**
     * <pre>
     * seqNo used to track ack
     * </pre>
     *
     * <code>uint32 seqNo = 1;</code>
     * @return The seqNo.
     */
    @java.lang.Override
    public int getSeqNo() {
      return seqNo_;
    }
    /**
     * <pre>
     * seqNo used to track ack
     * </pre>
     *
     * <code>uint32 seqNo = 1;</code>
     * @param value The seqNo to set.
     * @return This builder for chaining.
     */
    public Builder setSeqNo(int value) {
      
      seqNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * seqNo used to track ack
     * </pre>
     *
     * <code>uint32 seqNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqNo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      seqNo_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * name of the target member
     * </pre>
     *
     * <code>bytes id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }
    /**
     * <pre>
     * name of the target member
     * </pre>
     *
     * <code>bytes id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the target member
     * </pre>
     *
     * <code>bytes id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString pingerId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * name of the pinger member
     * </pre>
     *
     * <code>bytes pingerId = 3;</code>
     * @return The pingerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPingerId() {
      return pingerId_;
    }
    /**
     * <pre>
     * name of the pinger member
     * </pre>
     *
     * <code>bytes pingerId = 3;</code>
     * @param value The pingerId to set.
     * @return This builder for chaining.
     */
    public Builder setPingerId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      pingerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of the pinger member
     * </pre>
     *
     * <code>bytes pingerId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPingerId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pingerId_ = getDefaultInstance().getPingerId();
      onChanged();
      return this;
    }

    private java.lang.Object pingerAddr_ = "";
    /**
     * <pre>
     * addr of the pinger member
     * </pre>
     *
     * <code>string pingerAddr = 4;</code>
     * @return The pingerAddr.
     */
    public java.lang.String getPingerAddr() {
      java.lang.Object ref = pingerAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pingerAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * addr of the pinger member
     * </pre>
     *
     * <code>string pingerAddr = 4;</code>
     * @return The bytes for pingerAddr.
     */
    public com.google.protobuf.ByteString
        getPingerAddrBytes() {
      java.lang.Object ref = pingerAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pingerAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * addr of the pinger member
     * </pre>
     *
     * <code>string pingerAddr = 4;</code>
     * @param value The pingerAddr to set.
     * @return This builder for chaining.
     */
    public Builder setPingerAddr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pingerAddr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * addr of the pinger member
     * </pre>
     *
     * <code>string pingerAddr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPingerAddr() {
      pingerAddr_ = getDefaultInstance().getPingerAddr();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * addr of the pinger member
     * </pre>
     *
     * <code>string pingerAddr = 4;</code>
     * @param value The bytes for pingerAddr to set.
     * @return This builder for chaining.
     */
    public Builder setPingerAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pingerAddr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int pingerPort_ ;
    /**
     * <pre>
     * port to the pinger member
     * </pre>
     *
     * <code>uint32 pingerPort = 5;</code>
     * @return The pingerPort.
     */
    @java.lang.Override
    public int getPingerPort() {
      return pingerPort_;
    }
    /**
     * <pre>
     * port to the pinger member
     * </pre>
     *
     * <code>uint32 pingerPort = 5;</code>
     * @param value The pingerPort to set.
     * @return This builder for chaining.
     */
    public Builder setPingerPort(int value) {
      
      pingerPort_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * port to the pinger member
     * </pre>
     *
     * <code>uint32 pingerPort = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPingerPort() {
      bitField0_ = (bitField0_ & ~0x00000010);
      pingerPort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basecluster.fd.Ping)
  }

  // @@protoc_insertion_point(class_scope:basecluster.fd.Ping)
  private static final com.zachary.bifromq.basecluster.fd.proto.Ping DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.basecluster.fd.proto.Ping();
  }

  public static com.zachary.bifromq.basecluster.fd.proto.Ping getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ping>
      PARSER = new com.google.protobuf.AbstractParser<Ping>() {
    @java.lang.Override
    public Ping parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ping> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ping> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.basecluster.fd.proto.Ping getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

