// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commontype/TopicMessage.proto

package com.zachary.bifromq.type;

public interface TopicMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:commontype.TopicMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>.commontype.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.commontype.Message message = 2;</code>
   * @return The message.
   */
  com.zachary.bifromq.type.Message getMessage();
  /**
   * <code>.commontype.Message message = 2;</code>
   */
  com.zachary.bifromq.type.MessageOrBuilder getMessageOrBuilder();

  /**
   * <code>.commontype.ClientInfo publisher = 3;</code>
   * @return Whether the publisher field is set.
   */
  boolean hasPublisher();
  /**
   * <code>.commontype.ClientInfo publisher = 3;</code>
   * @return The publisher.
   */
  com.zachary.bifromq.type.ClientInfo getPublisher();
  /**
   * <code>.commontype.ClientInfo publisher = 3;</code>
   */
  com.zachary.bifromq.type.ClientInfoOrBuilder getPublisherOrBuilder();
}
