// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basecluster/membership/Endorse.proto

package com.zachary.bifromq.basecluster.membership.proto;

public final class EndorseOuterClass {
  private EndorseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_basecluster_membership_Endorse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_basecluster_membership_Endorse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$basecluster/membership/Endorse.proto\022\026" +
      "basecluster.membership\032\'basecluster/memb" +
      "ership/HostMember.proto\"\216\001\n\007Endorse\0226\n\010e" +
      "ndpoint\030\001 \001(\0132$.basecluster.membership.H" +
      "ostEndpoint\022\023\n\013incarnation\030\002 \001(\r\0226\n\010repo" +
      "rter\030\003 \001(\0132$.basecluster.membership.Host" +
      "EndpointB6\n0com.zachary.bifromq.baseclus" +
      "ter.membership.protoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zachary.bifromq.basecluster.membership.proto.HostMemberOuterClass.getDescriptor(),
        });
    internal_static_basecluster_membership_Endorse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_basecluster_membership_Endorse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_basecluster_membership_Endorse_descriptor,
        new java.lang.String[] { "Endpoint", "Incarnation", "Reporter", });
    com.zachary.bifromq.basecluster.membership.proto.HostMemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
