// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sessiondict/SessionDictionaryService.proto

package com.zachary.bifromq.sessiondict.rpc.proto;

public interface QuitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sessiondict.Quit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <pre>
   * could be anything meaningful. e.g. kicker's address
   * </pre>
   *
   * <code>.commontype.ClientInfo killer = 2;</code>
   * @return Whether the killer field is set.
   */
  boolean hasKiller();
  /**
   * <pre>
   * could be anything meaningful. e.g. kicker's address
   * </pre>
   *
   * <code>.commontype.ClientInfo killer = 2;</code>
   * @return The killer.
   */
  com.zachary.bifromq.type.ClientInfo getKiller();
  /**
   * <pre>
   * could be anything meaningful. e.g. kicker's address
   * </pre>
   *
   * <code>.commontype.ClientInfo killer = 2;</code>
   */
  com.zachary.bifromq.type.ClientInfoOrBuilder getKillerOrBuilder();
}
