// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/raft/RaftMessage.proto

package com.zachary.bifromq.basekv.raft.proto;

/**
 * Protobuf type {@code basekv.raft.InstallSnapshot}
 */
public final class InstallSnapshot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basekv.raft.InstallSnapshot)
    InstallSnapshotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InstallSnapshot.newBuilder() to construct.
  private InstallSnapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InstallSnapshot() {
    leaderId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InstallSnapshot();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.basekv.raft.proto.RaftMessageOuterClass.internal_static_basekv_raft_InstallSnapshot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.basekv.raft.proto.RaftMessageOuterClass.internal_static_basekv_raft_InstallSnapshot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.class, com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.Builder.class);
  }

  public static final int LEADERID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object leaderId_ = "";
  /**
   * <code>string leaderId = 1;</code>
   * @return The leaderId.
   */
  @java.lang.Override
  public java.lang.String getLeaderId() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderId_ = s;
      return s;
    }
  }
  /**
   * <code>string leaderId = 1;</code>
   * @return The bytes for leaderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLeaderIdBytes() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 2;
  private com.zachary.bifromq.basekv.raft.proto.Snapshot snapshot_;
  /**
   * <code>.basekv.raft.Snapshot snapshot = 2;</code>
   * @return Whether the snapshot field is set.
   */
  @java.lang.Override
  public boolean hasSnapshot() {
    return snapshot_ != null;
  }
  /**
   * <code>.basekv.raft.Snapshot snapshot = 2;</code>
   * @return The snapshot.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.Snapshot getSnapshot() {
    return snapshot_ == null ? com.zachary.bifromq.basekv.raft.proto.Snapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <code>.basekv.raft.Snapshot snapshot = 2;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
    return snapshot_ == null ? com.zachary.bifromq.basekv.raft.proto.Snapshot.getDefaultInstance() : snapshot_;
  }

  public static final int READINDEX_FIELD_NUMBER = 3;
  private long readIndex_ = 0L;
  /**
   * <pre>
   * read index to confirm
   * </pre>
   *
   * <code>uint64 readIndex = 3;</code>
   * @return The readIndex.
   */
  @java.lang.Override
  public long getReadIndex() {
    return readIndex_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, leaderId_);
    }
    if (snapshot_ != null) {
      output.writeMessage(2, getSnapshot());
    }
    if (readIndex_ != 0L) {
      output.writeUInt64(3, readIndex_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, leaderId_);
    }
    if (snapshot_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSnapshot());
    }
    if (readIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, readIndex_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.basekv.raft.proto.InstallSnapshot)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.basekv.raft.proto.InstallSnapshot other = (com.zachary.bifromq.basekv.raft.proto.InstallSnapshot) obj;

    if (!getLeaderId()
        .equals(other.getLeaderId())) return false;
    if (hasSnapshot() != other.hasSnapshot()) return false;
    if (hasSnapshot()) {
      if (!getSnapshot()
          .equals(other.getSnapshot())) return false;
    }
    if (getReadIndex()
        != other.getReadIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEADERID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId().hashCode();
    if (hasSnapshot()) {
      hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshot().hashCode();
    }
    hash = (37 * hash) + READINDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReadIndex());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.basekv.raft.proto.InstallSnapshot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code basekv.raft.InstallSnapshot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basekv.raft.InstallSnapshot)
      com.zachary.bifromq.basekv.raft.proto.InstallSnapshotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.basekv.raft.proto.RaftMessageOuterClass.internal_static_basekv_raft_InstallSnapshot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.basekv.raft.proto.RaftMessageOuterClass.internal_static_basekv_raft_InstallSnapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.class, com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.Builder.class);
    }

    // Construct using com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leaderId_ = "";
      snapshot_ = null;
      if (snapshotBuilder_ != null) {
        snapshotBuilder_.dispose();
        snapshotBuilder_ = null;
      }
      readIndex_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.basekv.raft.proto.RaftMessageOuterClass.internal_static_basekv_raft_InstallSnapshot_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.raft.proto.InstallSnapshot getDefaultInstanceForType() {
      return com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.raft.proto.InstallSnapshot build() {
      com.zachary.bifromq.basekv.raft.proto.InstallSnapshot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.raft.proto.InstallSnapshot buildPartial() {
      com.zachary.bifromq.basekv.raft.proto.InstallSnapshot result = new com.zachary.bifromq.basekv.raft.proto.InstallSnapshot(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.zachary.bifromq.basekv.raft.proto.InstallSnapshot result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leaderId_ = leaderId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.snapshot_ = snapshotBuilder_ == null
            ? snapshot_
            : snapshotBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.readIndex_ = readIndex_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.basekv.raft.proto.InstallSnapshot) {
        return mergeFrom((com.zachary.bifromq.basekv.raft.proto.InstallSnapshot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.basekv.raft.proto.InstallSnapshot other) {
      if (other == com.zachary.bifromq.basekv.raft.proto.InstallSnapshot.getDefaultInstance()) return this;
      if (!other.getLeaderId().isEmpty()) {
        leaderId_ = other.leaderId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasSnapshot()) {
        mergeSnapshot(other.getSnapshot());
      }
      if (other.getReadIndex() != 0L) {
        setReadIndex(other.getReadIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              leaderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getSnapshotFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              readIndex_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object leaderId_ = "";
    /**
     * <code>string leaderId = 1;</code>
     * @return The leaderId.
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leaderId = 1;</code>
     * @return The bytes for leaderId.
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leaderId = 1;</code>
     * @param value The leaderId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      leaderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string leaderId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaderId() {
      leaderId_ = getDefaultInstance().getLeaderId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string leaderId = 1;</code>
     * @param value The bytes for leaderId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      leaderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.zachary.bifromq.basekv.raft.proto.Snapshot snapshot_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.raft.proto.Snapshot, com.zachary.bifromq.basekv.raft.proto.Snapshot.Builder, com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder> snapshotBuilder_;
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     * @return Whether the snapshot field is set.
     */
    public boolean hasSnapshot() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     * @return The snapshot.
     */
    public com.zachary.bifromq.basekv.raft.proto.Snapshot getSnapshot() {
      if (snapshotBuilder_ == null) {
        return snapshot_ == null ? com.zachary.bifromq.basekv.raft.proto.Snapshot.getDefaultInstance() : snapshot_;
      } else {
        return snapshotBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public Builder setSnapshot(com.zachary.bifromq.basekv.raft.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snapshot_ = value;
      } else {
        snapshotBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public Builder setSnapshot(
        com.zachary.bifromq.basekv.raft.proto.Snapshot.Builder builderForValue) {
      if (snapshotBuilder_ == null) {
        snapshot_ = builderForValue.build();
      } else {
        snapshotBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public Builder mergeSnapshot(com.zachary.bifromq.basekv.raft.proto.Snapshot value) {
      if (snapshotBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          snapshot_ != null &&
          snapshot_ != com.zachary.bifromq.basekv.raft.proto.Snapshot.getDefaultInstance()) {
          getSnapshotBuilder().mergeFrom(value);
        } else {
          snapshot_ = value;
        }
      } else {
        snapshotBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public Builder clearSnapshot() {
      bitField0_ = (bitField0_ & ~0x00000002);
      snapshot_ = null;
      if (snapshotBuilder_ != null) {
        snapshotBuilder_.dispose();
        snapshotBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public com.zachary.bifromq.basekv.raft.proto.Snapshot.Builder getSnapshotBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    public com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder getSnapshotOrBuilder() {
      if (snapshotBuilder_ != null) {
        return snapshotBuilder_.getMessageOrBuilder();
      } else {
        return snapshot_ == null ?
            com.zachary.bifromq.basekv.raft.proto.Snapshot.getDefaultInstance() : snapshot_;
      }
    }
    /**
     * <code>.basekv.raft.Snapshot snapshot = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.raft.proto.Snapshot, com.zachary.bifromq.basekv.raft.proto.Snapshot.Builder, com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder> 
        getSnapshotFieldBuilder() {
      if (snapshotBuilder_ == null) {
        snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.raft.proto.Snapshot, com.zachary.bifromq.basekv.raft.proto.Snapshot.Builder, com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder>(
                getSnapshot(),
                getParentForChildren(),
                isClean());
        snapshot_ = null;
      }
      return snapshotBuilder_;
    }

    private long readIndex_ ;
    /**
     * <pre>
     * read index to confirm
     * </pre>
     *
     * <code>uint64 readIndex = 3;</code>
     * @return The readIndex.
     */
    @java.lang.Override
    public long getReadIndex() {
      return readIndex_;
    }
    /**
     * <pre>
     * read index to confirm
     * </pre>
     *
     * <code>uint64 readIndex = 3;</code>
     * @param value The readIndex to set.
     * @return This builder for chaining.
     */
    public Builder setReadIndex(long value) {
      
      readIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * read index to confirm
     * </pre>
     *
     * <code>uint64 readIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      readIndex_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basekv.raft.InstallSnapshot)
  }

  // @@protoc_insertion_point(class_scope:basekv.raft.InstallSnapshot)
  private static final com.zachary.bifromq.basekv.raft.proto.InstallSnapshot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.basekv.raft.proto.InstallSnapshot();
  }

  public static com.zachary.bifromq.basekv.raft.proto.InstallSnapshot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstallSnapshot>
      PARSER = new com.google.protobuf.AbstractParser<InstallSnapshot>() {
    @java.lang.Override
    public InstallSnapshot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InstallSnapshot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstallSnapshot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.InstallSnapshot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

