// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/raft/RaftMessage.proto

package com.zachary.bifromq.basekv.raft.proto;

public interface RequestPreVoteReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.raft.RequestPreVoteReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool voteCouldGranted = 1;</code>
   * @return The voteCouldGranted.
   */
  boolean getVoteCouldGranted();
}
