// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/Command.proto

package com.zachary.bifromq.basekv.proto;

public interface CancelMergingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.CancelMerging)
    com.google.protobuf.MessageOrBuilder {
}
