// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/StoreMessage.proto

package com.zachary.bifromq.basekv.proto;

public interface EnsureRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.EnsureRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.basekv.raft.Snapshot initSnapshot = 1;</code>
   * @return Whether the initSnapshot field is set.
   */
  boolean hasInitSnapshot();
  /**
   * <code>.basekv.raft.Snapshot initSnapshot = 1;</code>
   * @return The initSnapshot.
   */
  com.zachary.bifromq.basekv.raft.proto.Snapshot getInitSnapshot();
  /**
   * <code>.basekv.raft.Snapshot initSnapshot = 1;</code>
   */
  com.zachary.bifromq.basekv.raft.proto.SnapshotOrBuilder getInitSnapshotOrBuilder();
}
