// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/Type.proto

package com.zachary.bifromq.basekv.proto;

public interface KVRangeIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.KVRangeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 epoch = 1;</code>
   * @return The epoch.
   */
  long getEpoch();

  /**
   * <code>uint64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
