// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/Descriptor.proto

package com.zachary.bifromq.basekv.proto;

/**
 * Protobuf type {@code basekv.KVRangeDescriptor}
 */
public final class KVRangeDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basekv.KVRangeDescriptor)
    KVRangeDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KVRangeDescriptor.newBuilder() to construct.
  private KVRangeDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KVRangeDescriptor() {
    state_ = 0;
    role_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KVRangeDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetSyncState();
      case 8:
        return internalGetStatistics();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.basekv.proto.KVRangeDescriptor.class, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.zachary.bifromq.basekv.proto.KVRangeId id_;
  /**
   * <code>.basekv.KVRangeId id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.basekv.KVRangeId id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeId getId() {
    return id_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : id_;
  }
  /**
   * <code>.basekv.KVRangeId id = 1;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : id_;
  }

  public static final int VER_FIELD_NUMBER = 2;
  private long ver_ = 0L;
  /**
   * <code>uint64 ver = 2;</code>
   * @return The ver.
   */
  @java.lang.Override
  public long getVer() {
    return ver_;
  }

  public static final int RANGE_FIELD_NUMBER = 3;
  private com.zachary.bifromq.basekv.proto.Range range_;
  /**
   * <code>.basekv.Range range = 3;</code>
   * @return Whether the range field is set.
   */
  @java.lang.Override
  public boolean hasRange() {
    return range_ != null;
  }
  /**
   * <code>.basekv.Range range = 3;</code>
   * @return The range.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.Range getRange() {
    return range_ == null ? com.zachary.bifromq.basekv.proto.Range.getDefaultInstance() : range_;
  }
  /**
   * <code>.basekv.Range range = 3;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.RangeOrBuilder getRangeOrBuilder() {
    return range_ == null ? com.zachary.bifromq.basekv.proto.Range.getDefaultInstance() : range_;
  }

  public static final int STATE_FIELD_NUMBER = 4;
  private int state_ = 0;
  /**
   * <code>.basekv.State.StateType state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.basekv.State.StateType state = 4;</code>
   * @return The state.
   */
  @java.lang.Override public com.zachary.bifromq.basekv.proto.State.StateType getState() {
    com.zachary.bifromq.basekv.proto.State.StateType result = com.zachary.bifromq.basekv.proto.State.StateType.forNumber(state_);
    return result == null ? com.zachary.bifromq.basekv.proto.State.StateType.UNRECOGNIZED : result;
  }

  public static final int ROLE_FIELD_NUMBER = 5;
  private int role_ = 0;
  /**
   * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
   * @return The enum numeric value on the wire for role.
   */
  @java.lang.Override public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
   * @return The role.
   */
  @java.lang.Override public com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus getRole() {
    com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus result = com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.forNumber(role_);
    return result == null ? com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.UNRECOGNIZED : result;
  }

  public static final int CONFIG_FIELD_NUMBER = 6;
  private com.zachary.bifromq.basekv.raft.proto.ClusterConfig config_;
  /**
   * <code>.basekv.raft.ClusterConfig config = 6;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return config_ != null;
  }
  /**
   * <code>.basekv.raft.ClusterConfig config = 6;</code>
   * @return The config.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.ClusterConfig getConfig() {
    return config_ == null ? com.zachary.bifromq.basekv.raft.proto.ClusterConfig.getDefaultInstance() : config_;
  }
  /**
   * <code>.basekv.raft.ClusterConfig config = 6;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? com.zachary.bifromq.basekv.raft.proto.ClusterConfig.getDefaultInstance() : config_;
  }

  public static final int SYNCSTATE_FIELD_NUMBER = 7;
  private static final class SyncStateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_SyncStateEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.ENUM,
                com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState.Probing.getNumber());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> syncState_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetSyncState() {
    if (syncState_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SyncStateDefaultEntryHolder.defaultEntry);
    }
    return syncState_;
  }
  private static final
  com.google.protobuf.Internal.MapAdapter.Converter<
      java.lang.Integer, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState> syncStateValueConverter =
          com.google.protobuf.Internal.MapAdapter.newEnumConverter(
              com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState.internalGetValueMap(),
              com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState.UNRECOGNIZED);
  private static final java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
  internalGetAdaptedSyncStateMap(
      java.util.Map<java.lang.String, java.lang.Integer> map) {
    return new com.google.protobuf.Internal.MapAdapter<
        java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState, java.lang.Integer>(
            map, syncStateValueConverter);
  }
  public int getSyncStateCount() {
    return internalGetSyncState().getMap().size();
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public boolean containsSyncState(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetSyncState().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSyncStateMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
  getSyncState() {
    return getSyncStateMap();
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
  getSyncStateMap() {
    return internalGetAdaptedSyncStateMap(
        internalGetSyncState().getMap());}
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public /* nullable */
com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState getSyncStateOrDefault(
      java.lang.String key,
      /* nullable */
com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSyncState().getMap();
    return map.containsKey(key)
           ? syncStateValueConverter.doForward(map.get(key))
           : defaultValue;
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState getSyncStateOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSyncState().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return syncStateValueConverter.doForward(map.get(key));
  }
  /**
   * Use {@link #getSyncStateValueMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer>
  getSyncStateValue() {
    return getSyncStateValueMap();
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Integer>
  getSyncStateValueMap() {
    return internalGetSyncState().getMap();
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public int getSyncStateValueOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSyncState().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
   */
  @java.lang.Override
  public int getSyncStateValueOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetSyncState().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STATISTICS_FIELD_NUMBER = 8;
  private static final class StatisticsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Double>newDefaultInstance(
                com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_StatisticsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Double> statistics_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
  internalGetStatistics() {
    if (statistics_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StatisticsDefaultEntryHolder.defaultEntry);
    }
    return statistics_;
  }
  public int getStatisticsCount() {
    return internalGetStatistics().getMap().size();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 8;</code>
   */
  @java.lang.Override
  public boolean containsStatistics(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStatistics().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStatisticsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Double> getStatistics() {
    return getStatisticsMap();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 8;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Double> getStatisticsMap() {
    return internalGetStatistics().getMap();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 8;</code>
   */
  @java.lang.Override
  public double getStatisticsOrDefault(
      java.lang.String key,
      double defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetStatistics().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 8;</code>
   */
  @java.lang.Override
  public double getStatisticsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetStatistics().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LOADHINT_FIELD_NUMBER = 9;
  private com.zachary.bifromq.basekv.proto.LoadHint loadHint_;
  /**
   * <code>.basekv.LoadHint loadHint = 9;</code>
   * @return Whether the loadHint field is set.
   */
  @java.lang.Override
  public boolean hasLoadHint() {
    return loadHint_ != null;
  }
  /**
   * <code>.basekv.LoadHint loadHint = 9;</code>
   * @return The loadHint.
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.LoadHint getLoadHint() {
    return loadHint_ == null ? com.zachary.bifromq.basekv.proto.LoadHint.getDefaultInstance() : loadHint_;
  }
  /**
   * <code>.basekv.LoadHint loadHint = 9;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.LoadHintOrBuilder getLoadHintOrBuilder() {
    return loadHint_ == null ? com.zachary.bifromq.basekv.proto.LoadHint.getDefaultInstance() : loadHint_;
  }

  public static final int HLC_FIELD_NUMBER = 10;
  private long hlc_ = 0L;
  /**
   * <code>uint64 hlc = 10;</code>
   * @return The hlc.
   */
  @java.lang.Override
  public long getHlc() {
    return hlc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (ver_ != 0L) {
      output.writeUInt64(2, ver_);
    }
    if (range_ != null) {
      output.writeMessage(3, getRange());
    }
    if (state_ != com.zachary.bifromq.basekv.proto.State.StateType.NoUse.getNumber()) {
      output.writeEnum(4, state_);
    }
    if (role_ != com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.Follower.getNumber()) {
      output.writeEnum(5, role_);
    }
    if (config_ != null) {
      output.writeMessage(6, getConfig());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetSyncState(),
        SyncStateDefaultEntryHolder.defaultEntry,
        7);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetStatistics(),
        StatisticsDefaultEntryHolder.defaultEntry,
        8);
    if (loadHint_ != null) {
      output.writeMessage(9, getLoadHint());
    }
    if (hlc_ != 0L) {
      output.writeUInt64(10, hlc_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (ver_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ver_);
    }
    if (range_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRange());
    }
    if (state_ != com.zachary.bifromq.basekv.proto.State.StateType.NoUse.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, state_);
    }
    if (role_ != com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.Follower.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, role_);
    }
    if (config_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getConfig());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetSyncState().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      syncState__ = SyncStateDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, syncState__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
         : internalGetStatistics().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
      statistics__ = StatisticsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, statistics__);
    }
    if (loadHint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getLoadHint());
    }
    if (hlc_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, hlc_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.basekv.proto.KVRangeDescriptor)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.basekv.proto.KVRangeDescriptor other = (com.zachary.bifromq.basekv.proto.KVRangeDescriptor) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (getVer()
        != other.getVer()) return false;
    if (hasRange() != other.hasRange()) return false;
    if (hasRange()) {
      if (!getRange()
          .equals(other.getRange())) return false;
    }
    if (state_ != other.state_) return false;
    if (role_ != other.role_) return false;
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!internalGetSyncState().equals(
        other.internalGetSyncState())) return false;
    if (!internalGetStatistics().equals(
        other.internalGetStatistics())) return false;
    if (hasLoadHint() != other.hasLoadHint()) return false;
    if (hasLoadHint()) {
      if (!getLoadHint()
          .equals(other.getLoadHint())) return false;
    }
    if (getHlc()
        != other.getHlc()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + VER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVer());
    if (hasRange()) {
      hash = (37 * hash) + RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getRange().hashCode();
    }
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    if (!internalGetSyncState().getMap().isEmpty()) {
      hash = (37 * hash) + SYNCSTATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSyncState().hashCode();
    }
    if (!internalGetStatistics().getMap().isEmpty()) {
      hash = (37 * hash) + STATISTICS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStatistics().hashCode();
    }
    if (hasLoadHint()) {
      hash = (37 * hash) + LOADHINT_FIELD_NUMBER;
      hash = (53 * hash) + getLoadHint().hashCode();
    }
    hash = (37 * hash) + HLC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHlc());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.basekv.proto.KVRangeDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code basekv.KVRangeDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basekv.KVRangeDescriptor)
      com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetSyncState();
        case 8:
          return internalGetStatistics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableSyncState();
        case 8:
          return internalGetMutableStatistics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.basekv.proto.KVRangeDescriptor.class, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder.class);
    }

    // Construct using com.zachary.bifromq.basekv.proto.KVRangeDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      ver_ = 0L;
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      state_ = 0;
      role_ = 0;
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      internalGetMutableSyncState().clear();
      internalGetMutableStatistics().clear();
      loadHint_ = null;
      if (loadHintBuilder_ != null) {
        loadHintBuilder_.dispose();
        loadHintBuilder_ = null;
      }
      hlc_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeDescriptor_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor getDefaultInstanceForType() {
      return com.zachary.bifromq.basekv.proto.KVRangeDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor build() {
      com.zachary.bifromq.basekv.proto.KVRangeDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor buildPartial() {
      com.zachary.bifromq.basekv.proto.KVRangeDescriptor result = new com.zachary.bifromq.basekv.proto.KVRangeDescriptor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.zachary.bifromq.basekv.proto.KVRangeDescriptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ver_ = ver_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.range_ = rangeBuilder_ == null
            ? range_
            : rangeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.role_ = role_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.syncState_ = internalGetSyncState();
        result.syncState_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.statistics_ = internalGetStatistics();
        result.statistics_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.loadHint_ = loadHintBuilder_ == null
            ? loadHint_
            : loadHintBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.hlc_ = hlc_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.basekv.proto.KVRangeDescriptor) {
        return mergeFrom((com.zachary.bifromq.basekv.proto.KVRangeDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.basekv.proto.KVRangeDescriptor other) {
      if (other == com.zachary.bifromq.basekv.proto.KVRangeDescriptor.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.getVer() != 0L) {
        setVer(other.getVer());
      }
      if (other.hasRange()) {
        mergeRange(other.getRange());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      internalGetMutableSyncState().mergeFrom(
          other.internalGetSyncState());
      bitField0_ |= 0x00000040;
      internalGetMutableStatistics().mergeFrom(
          other.internalGetStatistics());
      bitField0_ |= 0x00000080;
      if (other.hasLoadHint()) {
        mergeLoadHint(other.getLoadHint());
      }
      if (other.getHlc() != 0L) {
        setHlc(other.getHlc());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              ver_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              role_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              syncState__ = input.readMessage(
                  SyncStateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableSyncState().getMutableMap().put(
                  syncState__.getKey(), syncState__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              statistics__ = input.readMessage(
                  StatisticsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStatistics().getMutableMap().put(
                  statistics__.getKey(), statistics__.getValue());
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getLoadHintFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              hlc_ = input.readUInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.zachary.bifromq.basekv.proto.KVRangeId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder> idBuilder_;
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     * @return The id.
     */
    public com.zachary.bifromq.basekv.proto.KVRangeId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public Builder setId(com.zachary.bifromq.basekv.proto.KVRangeId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public Builder setId(
        com.zachary.bifromq.basekv.proto.KVRangeId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public Builder mergeId(com.zachary.bifromq.basekv.proto.KVRangeId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeId.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.zachary.bifromq.basekv.proto.KVRangeId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.basekv.KVRangeId id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.proto.KVRangeId, com.zachary.bifromq.basekv.proto.KVRangeId.Builder, com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private long ver_ ;
    /**
     * <code>uint64 ver = 2;</code>
     * @return The ver.
     */
    @java.lang.Override
    public long getVer() {
      return ver_;
    }
    /**
     * <code>uint64 ver = 2;</code>
     * @param value The ver to set.
     * @return This builder for chaining.
     */
    public Builder setVer(long value) {
      
      ver_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ver = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVer() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ver_ = 0L;
      onChanged();
      return this;
    }

    private com.zachary.bifromq.basekv.proto.Range range_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.Range, com.zachary.bifromq.basekv.proto.Range.Builder, com.zachary.bifromq.basekv.proto.RangeOrBuilder> rangeBuilder_;
    /**
     * <code>.basekv.Range range = 3;</code>
     * @return Whether the range field is set.
     */
    public boolean hasRange() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     * @return The range.
     */
    public com.zachary.bifromq.basekv.proto.Range getRange() {
      if (rangeBuilder_ == null) {
        return range_ == null ? com.zachary.bifromq.basekv.proto.Range.getDefaultInstance() : range_;
      } else {
        return rangeBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public Builder setRange(com.zachary.bifromq.basekv.proto.Range value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        range_ = value;
      } else {
        rangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public Builder setRange(
        com.zachary.bifromq.basekv.proto.Range.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        range_ = builderForValue.build();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public Builder mergeRange(com.zachary.bifromq.basekv.proto.Range value) {
      if (rangeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          range_ != null &&
          range_ != com.zachary.bifromq.basekv.proto.Range.getDefaultInstance()) {
          getRangeBuilder().mergeFrom(value);
        } else {
          range_ = value;
        }
      } else {
        rangeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public Builder clearRange() {
      bitField0_ = (bitField0_ & ~0x00000004);
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.Range.Builder getRangeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.RangeOrBuilder getRangeOrBuilder() {
      if (rangeBuilder_ != null) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        return range_ == null ?
            com.zachary.bifromq.basekv.proto.Range.getDefaultInstance() : range_;
      }
    }
    /**
     * <code>.basekv.Range range = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.Range, com.zachary.bifromq.basekv.proto.Range.Builder, com.zachary.bifromq.basekv.proto.RangeOrBuilder> 
        getRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.proto.Range, com.zachary.bifromq.basekv.proto.Range.Builder, com.zachary.bifromq.basekv.proto.RangeOrBuilder>(
                getRange(),
                getParentForChildren(),
                isClean());
        range_ = null;
      }
      return rangeBuilder_;
    }

    private int state_ = 0;
    /**
     * <code>.basekv.State.StateType state = 4;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.basekv.State.StateType state = 4;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.State.StateType state = 4;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.State.StateType getState() {
      com.zachary.bifromq.basekv.proto.State.StateType result = com.zachary.bifromq.basekv.proto.State.StateType.forNumber(state_);
      return result == null ? com.zachary.bifromq.basekv.proto.State.StateType.UNRECOGNIZED : result;
    }
    /**
     * <code>.basekv.State.StateType state = 4;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.zachary.bifromq.basekv.proto.State.StateType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.State.StateType state = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000008);
      state_ = 0;
      onChanged();
      return this;
    }

    private int role_ = 0;
    /**
     * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
     * @return The role.
     */
    @java.lang.Override
    public com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus getRole() {
      com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus result = com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.forNumber(role_);
      return result == null ? com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(com.zachary.bifromq.basekv.raft.proto.RaftNodeStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.RaftNodeStatus role = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      bitField0_ = (bitField0_ & ~0x00000010);
      role_ = 0;
      onChanged();
      return this;
    }

    private com.zachary.bifromq.basekv.raft.proto.ClusterConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.raft.proto.ClusterConfig, com.zachary.bifromq.basekv.raft.proto.ClusterConfig.Builder, com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder> configBuilder_;
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     * @return The config.
     */
    public com.zachary.bifromq.basekv.raft.proto.ClusterConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? com.zachary.bifromq.basekv.raft.proto.ClusterConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public Builder setConfig(com.zachary.bifromq.basekv.raft.proto.ClusterConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public Builder setConfig(
        com.zachary.bifromq.basekv.raft.proto.ClusterConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public Builder mergeConfig(com.zachary.bifromq.basekv.raft.proto.ClusterConfig value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          config_ != null &&
          config_ != com.zachary.bifromq.basekv.raft.proto.ClusterConfig.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000020);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public com.zachary.bifromq.basekv.raft.proto.ClusterConfig.Builder getConfigBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    public com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            com.zachary.bifromq.basekv.raft.proto.ClusterConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>.basekv.raft.ClusterConfig config = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.raft.proto.ClusterConfig, com.zachary.bifromq.basekv.raft.proto.ClusterConfig.Builder, com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.raft.proto.ClusterConfig, com.zachary.bifromq.basekv.raft.proto.ClusterConfig.Builder, com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> syncState_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetSyncState() {
      if (syncState_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SyncStateDefaultEntryHolder.defaultEntry);
      }
      return syncState_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
        internalGetMutableSyncState() {
      if (syncState_ == null) {
        syncState_ = com.google.protobuf.MapField.newMapField(
            SyncStateDefaultEntryHolder.defaultEntry);
      }
      if (!syncState_.isMutable()) {
        syncState_ = syncState_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return syncState_;
    }
    public int getSyncStateCount() {
      return internalGetSyncState().getMap().size();
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public boolean containsSyncState(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSyncState().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSyncStateMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
    getSyncState() {
      return getSyncStateMap();
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
    getSyncStateMap() {
      return internalGetAdaptedSyncStateMap(
          internalGetSyncState().getMap());}
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState getSyncStateOrDefault(
        java.lang.String key,
        /* nullable */
com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSyncState().getMap();
      return map.containsKey(key)
             ? syncStateValueConverter.doForward(map.get(key))
             : defaultValue;
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState getSyncStateOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSyncState().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return syncStateValueConverter.doForward(map.get(key));
    }
    /**
     * Use {@link #getSyncStateValueMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getSyncStateValue() {
      return getSyncStateValueMap();
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Integer>
    getSyncStateValueMap() {
      return internalGetSyncState().getMap();
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public int getSyncStateValueOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSyncState().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    @java.lang.Override
    public int getSyncStateValueOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSyncState().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearSyncState() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableSyncState().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    public Builder removeSyncState(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableSyncState().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState>
        getMutableSyncState() {
      bitField0_ |= 0x00000040;
      return internalGetAdaptedSyncStateMap(
           internalGetMutableSyncState().getMutableMap());
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    public Builder putSyncState(
        java.lang.String key,
        com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableSyncState().getMutableMap()
          .put(key, syncStateValueConverter.doBackward(value));
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    public Builder putAllSyncState(
        java.util.Map<java.lang.String, com.zachary.bifromq.basekv.raft.proto.RaftNodeSyncState> values) {
      internalGetAdaptedSyncStateMap(
          internalGetMutableSyncState().getMutableMap())
              .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutableSyncStateValue() {
      bitField0_ |= 0x00000040;
      return internalGetMutableSyncState().getMutableMap();
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    public Builder putSyncStateValue(
        java.lang.String key,
        int value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableSyncState().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, .basekv.raft.RaftNodeSyncState&gt; syncState = 7;</code>
     */
    public Builder putAllSyncStateValue(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      internalGetMutableSyncState().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> statistics_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetStatistics() {
      if (statistics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatisticsDefaultEntryHolder.defaultEntry);
      }
      return statistics_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMutableStatistics() {
      if (statistics_ == null) {
        statistics_ = com.google.protobuf.MapField.newMapField(
            StatisticsDefaultEntryHolder.defaultEntry);
      }
      if (!statistics_.isMutable()) {
        statistics_ = statistics_.copy();
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return statistics_;
    }
    public int getStatisticsCount() {
      return internalGetStatistics().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    @java.lang.Override
    public boolean containsStatistics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStatistics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatisticsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getStatistics() {
      return getStatisticsMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Double> getStatisticsMap() {
      return internalGetStatistics().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    @java.lang.Override
    public double getStatisticsOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetStatistics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    @java.lang.Override
    public double getStatisticsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetStatistics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearStatistics() {
      bitField0_ = (bitField0_ & ~0x00000080);
      internalGetMutableStatistics().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    public Builder removeStatistics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStatistics().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double>
        getMutableStatistics() {
      bitField0_ |= 0x00000080;
      return internalGetMutableStatistics().getMutableMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    public Builder putStatistics(
        java.lang.String key,
        double value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableStatistics().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 8;</code>
     */
    public Builder putAllStatistics(
        java.util.Map<java.lang.String, java.lang.Double> values) {
      internalGetMutableStatistics().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000080;
      return this;
    }

    private com.zachary.bifromq.basekv.proto.LoadHint loadHint_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.LoadHint, com.zachary.bifromq.basekv.proto.LoadHint.Builder, com.zachary.bifromq.basekv.proto.LoadHintOrBuilder> loadHintBuilder_;
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     * @return Whether the loadHint field is set.
     */
    public boolean hasLoadHint() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     * @return The loadHint.
     */
    public com.zachary.bifromq.basekv.proto.LoadHint getLoadHint() {
      if (loadHintBuilder_ == null) {
        return loadHint_ == null ? com.zachary.bifromq.basekv.proto.LoadHint.getDefaultInstance() : loadHint_;
      } else {
        return loadHintBuilder_.getMessage();
      }
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public Builder setLoadHint(com.zachary.bifromq.basekv.proto.LoadHint value) {
      if (loadHintBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loadHint_ = value;
      } else {
        loadHintBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public Builder setLoadHint(
        com.zachary.bifromq.basekv.proto.LoadHint.Builder builderForValue) {
      if (loadHintBuilder_ == null) {
        loadHint_ = builderForValue.build();
      } else {
        loadHintBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public Builder mergeLoadHint(com.zachary.bifromq.basekv.proto.LoadHint value) {
      if (loadHintBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          loadHint_ != null &&
          loadHint_ != com.zachary.bifromq.basekv.proto.LoadHint.getDefaultInstance()) {
          getLoadHintBuilder().mergeFrom(value);
        } else {
          loadHint_ = value;
        }
      } else {
        loadHintBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public Builder clearLoadHint() {
      bitField0_ = (bitField0_ & ~0x00000100);
      loadHint_ = null;
      if (loadHintBuilder_ != null) {
        loadHintBuilder_.dispose();
        loadHintBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public com.zachary.bifromq.basekv.proto.LoadHint.Builder getLoadHintBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getLoadHintFieldBuilder().getBuilder();
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    public com.zachary.bifromq.basekv.proto.LoadHintOrBuilder getLoadHintOrBuilder() {
      if (loadHintBuilder_ != null) {
        return loadHintBuilder_.getMessageOrBuilder();
      } else {
        return loadHint_ == null ?
            com.zachary.bifromq.basekv.proto.LoadHint.getDefaultInstance() : loadHint_;
      }
    }
    /**
     * <code>.basekv.LoadHint loadHint = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.LoadHint, com.zachary.bifromq.basekv.proto.LoadHint.Builder, com.zachary.bifromq.basekv.proto.LoadHintOrBuilder> 
        getLoadHintFieldBuilder() {
      if (loadHintBuilder_ == null) {
        loadHintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.zachary.bifromq.basekv.proto.LoadHint, com.zachary.bifromq.basekv.proto.LoadHint.Builder, com.zachary.bifromq.basekv.proto.LoadHintOrBuilder>(
                getLoadHint(),
                getParentForChildren(),
                isClean());
        loadHint_ = null;
      }
      return loadHintBuilder_;
    }

    private long hlc_ ;
    /**
     * <code>uint64 hlc = 10;</code>
     * @return The hlc.
     */
    @java.lang.Override
    public long getHlc() {
      return hlc_;
    }
    /**
     * <code>uint64 hlc = 10;</code>
     * @param value The hlc to set.
     * @return This builder for chaining.
     */
    public Builder setHlc(long value) {
      
      hlc_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 hlc = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearHlc() {
      bitField0_ = (bitField0_ & ~0x00000200);
      hlc_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basekv.KVRangeDescriptor)
  }

  // @@protoc_insertion_point(class_scope:basekv.KVRangeDescriptor)
  private static final com.zachary.bifromq.basekv.proto.KVRangeDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.basekv.proto.KVRangeDescriptor();
  }

  public static com.zachary.bifromq.basekv.proto.KVRangeDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KVRangeDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<KVRangeDescriptor>() {
    @java.lang.Override
    public KVRangeDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KVRangeDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KVRangeDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

