// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/Descriptor.proto

package com.zachary.bifromq.basekv.proto;

/**
 * Protobuf type {@code basekv.KVRangeStoreDescriptor}
 */
public final class KVRangeStoreDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basekv.KVRangeStoreDescriptor)
    KVRangeStoreDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KVRangeStoreDescriptor.newBuilder() to construct.
  private KVRangeStoreDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KVRangeStoreDescriptor() {
    id_ = "";
    ranges_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KVRangeStoreDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetStatistics();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.class, com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATISTICS_FIELD_NUMBER = 2;
  private static final class StatisticsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Double>newDefaultInstance(
                com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_StatisticsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Double> statistics_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
  internalGetStatistics() {
    if (statistics_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StatisticsDefaultEntryHolder.defaultEntry);
    }
    return statistics_;
  }
  public int getStatisticsCount() {
    return internalGetStatistics().getMap().size();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 2;</code>
   */
  @java.lang.Override
  public boolean containsStatistics(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStatistics().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStatisticsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Double> getStatistics() {
    return getStatisticsMap();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Double> getStatisticsMap() {
    return internalGetStatistics().getMap();
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 2;</code>
   */
  @java.lang.Override
  public double getStatisticsOrDefault(
      java.lang.String key,
      double defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetStatistics().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, double&gt; statistics = 2;</code>
   */
  @java.lang.Override
  public double getStatisticsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Double> map =
        internalGetStatistics().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int RANGES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.zachary.bifromq.basekv.proto.KVRangeDescriptor> ranges_;
  /**
   * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.zachary.bifromq.basekv.proto.KVRangeDescriptor> getRangesList() {
    return ranges_;
  }
  /**
   * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder> 
      getRangesOrBuilderList() {
    return ranges_;
  }
  /**
   * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
   */
  @java.lang.Override
  public int getRangesCount() {
    return ranges_.size();
  }
  /**
   * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeDescriptor getRanges(int index) {
    return ranges_.get(index);
  }
  /**
   * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
   */
  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder getRangesOrBuilder(
      int index) {
    return ranges_.get(index);
  }

  public static final int HLC_FIELD_NUMBER = 4;
  private long hlc_ = 0L;
  /**
   * <code>uint64 hlc = 4;</code>
   * @return The hlc.
   */
  @java.lang.Override
  public long getHlc() {
    return hlc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetStatistics(),
        StatisticsDefaultEntryHolder.defaultEntry,
        2);
    for (int i = 0; i < ranges_.size(); i++) {
      output.writeMessage(3, ranges_.get(i));
    }
    if (hlc_ != 0L) {
      output.writeUInt64(4, hlc_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
         : internalGetStatistics().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
      statistics__ = StatisticsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, statistics__);
    }
    for (int i = 0; i < ranges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, ranges_.get(i));
    }
    if (hlc_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, hlc_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor)) {
      return super.equals(obj);
    }
    com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor other = (com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!internalGetStatistics().equals(
        other.internalGetStatistics())) return false;
    if (!getRangesList()
        .equals(other.getRangesList())) return false;
    if (getHlc()
        != other.getHlc()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (!internalGetStatistics().getMap().isEmpty()) {
      hash = (37 * hash) + STATISTICS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStatistics().hashCode();
    }
    if (getRangesCount() > 0) {
      hash = (37 * hash) + RANGES_FIELD_NUMBER;
      hash = (53 * hash) + getRangesList().hashCode();
    }
    hash = (37 * hash) + HLC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHlc());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code basekv.KVRangeStoreDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basekv.KVRangeStoreDescriptor)
      com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetStatistics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableStatistics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.class, com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.Builder.class);
    }

    // Construct using com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      internalGetMutableStatistics().clear();
      if (rangesBuilder_ == null) {
        ranges_ = java.util.Collections.emptyList();
      } else {
        ranges_ = null;
        rangesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      hlc_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zachary.bifromq.basekv.proto.Descriptor.internal_static_basekv_KVRangeStoreDescriptor_descriptor;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor getDefaultInstanceForType() {
      return com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor build() {
      com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor buildPartial() {
      com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor result = new com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor result) {
      if (rangesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          ranges_ = java.util.Collections.unmodifiableList(ranges_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.ranges_ = ranges_;
      } else {
        result.ranges_ = rangesBuilder_.build();
      }
    }

    private void buildPartial0(com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.statistics_ = internalGetStatistics();
        result.statistics_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hlc_ = hlc_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor) {
        return mergeFrom((com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor other) {
      if (other == com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableStatistics().mergeFrom(
          other.internalGetStatistics());
      bitField0_ |= 0x00000002;
      if (rangesBuilder_ == null) {
        if (!other.ranges_.isEmpty()) {
          if (ranges_.isEmpty()) {
            ranges_ = other.ranges_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRangesIsMutable();
            ranges_.addAll(other.ranges_);
          }
          onChanged();
        }
      } else {
        if (!other.ranges_.isEmpty()) {
          if (rangesBuilder_.isEmpty()) {
            rangesBuilder_.dispose();
            rangesBuilder_ = null;
            ranges_ = other.ranges_;
            bitField0_ = (bitField0_ & ~0x00000004);
            rangesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRangesFieldBuilder() : null;
          } else {
            rangesBuilder_.addAllMessages(other.ranges_);
          }
        }
      }
      if (other.getHlc() != 0L) {
        setHlc(other.getHlc());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              statistics__ = input.readMessage(
                  StatisticsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStatistics().getMutableMap().put(
                  statistics__.getKey(), statistics__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.zachary.bifromq.basekv.proto.KVRangeDescriptor m =
                  input.readMessage(
                      com.zachary.bifromq.basekv.proto.KVRangeDescriptor.parser(),
                      extensionRegistry);
              if (rangesBuilder_ == null) {
                ensureRangesIsMutable();
                ranges_.add(m);
              } else {
                rangesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              hlc_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> statistics_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetStatistics() {
      if (statistics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatisticsDefaultEntryHolder.defaultEntry);
      }
      return statistics_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMutableStatistics() {
      if (statistics_ == null) {
        statistics_ = com.google.protobuf.MapField.newMapField(
            StatisticsDefaultEntryHolder.defaultEntry);
      }
      if (!statistics_.isMutable()) {
        statistics_ = statistics_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return statistics_;
    }
    public int getStatisticsCount() {
      return internalGetStatistics().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    @java.lang.Override
    public boolean containsStatistics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStatistics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatisticsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getStatistics() {
      return getStatisticsMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Double> getStatisticsMap() {
      return internalGetStatistics().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    @java.lang.Override
    public double getStatisticsOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetStatistics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    @java.lang.Override
    public double getStatisticsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetStatistics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearStatistics() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableStatistics().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    public Builder removeStatistics(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStatistics().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double>
        getMutableStatistics() {
      bitField0_ |= 0x00000002;
      return internalGetMutableStatistics().getMutableMap();
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    public Builder putStatistics(
        java.lang.String key,
        double value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableStatistics().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>map&lt;string, double&gt; statistics = 2;</code>
     */
    public Builder putAllStatistics(
        java.util.Map<java.lang.String, java.lang.Double> values) {
      internalGetMutableStatistics().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private java.util.List<com.zachary.bifromq.basekv.proto.KVRangeDescriptor> ranges_ =
      java.util.Collections.emptyList();
    private void ensureRangesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        ranges_ = new java.util.ArrayList<com.zachary.bifromq.basekv.proto.KVRangeDescriptor>(ranges_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeDescriptor, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder, com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder> rangesBuilder_;

    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public java.util.List<com.zachary.bifromq.basekv.proto.KVRangeDescriptor> getRangesList() {
      if (rangesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ranges_);
      } else {
        return rangesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public int getRangesCount() {
      if (rangesBuilder_ == null) {
        return ranges_.size();
      } else {
        return rangesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor getRanges(int index) {
      if (rangesBuilder_ == null) {
        return ranges_.get(index);
      } else {
        return rangesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder setRanges(
        int index, com.zachary.bifromq.basekv.proto.KVRangeDescriptor value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.set(index, value);
        onChanged();
      } else {
        rangesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder setRanges(
        int index, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.set(index, builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder addRanges(com.zachary.bifromq.basekv.proto.KVRangeDescriptor value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.add(value);
        onChanged();
      } else {
        rangesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder addRanges(
        int index, com.zachary.bifromq.basekv.proto.KVRangeDescriptor value) {
      if (rangesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRangesIsMutable();
        ranges_.add(index, value);
        onChanged();
      } else {
        rangesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder addRanges(
        com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.add(builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder addRanges(
        int index, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder builderForValue) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.add(index, builderForValue.build());
        onChanged();
      } else {
        rangesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder addAllRanges(
        java.lang.Iterable<? extends com.zachary.bifromq.basekv.proto.KVRangeDescriptor> values) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ranges_);
        onChanged();
      } else {
        rangesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder clearRanges() {
      if (rangesBuilder_ == null) {
        ranges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        rangesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public Builder removeRanges(int index) {
      if (rangesBuilder_ == null) {
        ensureRangesIsMutable();
        ranges_.remove(index);
        onChanged();
      } else {
        rangesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder getRangesBuilder(
        int index) {
      return getRangesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder getRangesOrBuilder(
        int index) {
      if (rangesBuilder_ == null) {
        return ranges_.get(index);  } else {
        return rangesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public java.util.List<? extends com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder> 
         getRangesOrBuilderList() {
      if (rangesBuilder_ != null) {
        return rangesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ranges_);
      }
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder addRangesBuilder() {
      return getRangesFieldBuilder().addBuilder(
          com.zachary.bifromq.basekv.proto.KVRangeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder addRangesBuilder(
        int index) {
      return getRangesFieldBuilder().addBuilder(
          index, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .basekv.KVRangeDescriptor ranges = 3;</code>
     */
    public java.util.List<com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder> 
         getRangesBuilderList() {
      return getRangesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zachary.bifromq.basekv.proto.KVRangeDescriptor, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder, com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder> 
        getRangesFieldBuilder() {
      if (rangesBuilder_ == null) {
        rangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zachary.bifromq.basekv.proto.KVRangeDescriptor, com.zachary.bifromq.basekv.proto.KVRangeDescriptor.Builder, com.zachary.bifromq.basekv.proto.KVRangeDescriptorOrBuilder>(
                ranges_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        ranges_ = null;
      }
      return rangesBuilder_;
    }

    private long hlc_ ;
    /**
     * <code>uint64 hlc = 4;</code>
     * @return The hlc.
     */
    @java.lang.Override
    public long getHlc() {
      return hlc_;
    }
    /**
     * <code>uint64 hlc = 4;</code>
     * @param value The hlc to set.
     * @return This builder for chaining.
     */
    public Builder setHlc(long value) {
      
      hlc_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 hlc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHlc() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hlc_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basekv.KVRangeStoreDescriptor)
  }

  // @@protoc_insertion_point(class_scope:basekv.KVRangeStoreDescriptor)
  private static final com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor();
  }

  public static com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KVRangeStoreDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<KVRangeStoreDescriptor>() {
    @java.lang.Override
    public KVRangeStoreDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KVRangeStoreDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KVRangeStoreDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zachary.bifromq.basekv.proto.KVRangeStoreDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

