// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/Command.proto

package com.zachary.bifromq.basekv.proto;

public interface MergeDoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.MergeDone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string storeId = 1;</code>
   * @return The storeId.
   */
  java.lang.String getStoreId();
  /**
   * <code>string storeId = 1;</code>
   * @return The bytes for storeId.
   */
  com.google.protobuf.ByteString
      getStoreIdBytes();
}
