// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basekv/StoreMessage.proto

package com.zachary.bifromq.basekv.proto;

public interface PrepareMergeToRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:basekv.PrepareMergeToRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string taskId = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string taskId = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * merger's id
   * </pre>
   *
   * <code>.basekv.KVRangeId id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * merger's id
   * </pre>
   *
   * <code>.basekv.KVRangeId id = 2;</code>
   * @return The id.
   */
  com.zachary.bifromq.basekv.proto.KVRangeId getId();
  /**
   * <pre>
   * merger's id
   * </pre>
   *
   * <code>.basekv.KVRangeId id = 2;</code>
   */
  com.zachary.bifromq.basekv.proto.KVRangeIdOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * merger's ver
   * </pre>
   *
   * <code>uint64 ver = 3;</code>
   * @return The ver.
   */
  long getVer();

  /**
   * <pre>
   * merger's config at the moment
   * </pre>
   *
   * <code>.basekv.raft.ClusterConfig config = 4;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * merger's config at the moment
   * </pre>
   *
   * <code>.basekv.raft.ClusterConfig config = 4;</code>
   * @return The config.
   */
  com.zachary.bifromq.basekv.raft.proto.ClusterConfig getConfig();
  /**
   * <pre>
   * merger's config at the moment
   * </pre>
   *
   * <code>.basekv.raft.ClusterConfig config = 4;</code>
   */
  com.zachary.bifromq.basekv.raft.proto.ClusterConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * merger's range at the moment
   * </pre>
   *
   * <code>.basekv.Range range = 5;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <pre>
   * merger's range at the moment
   * </pre>
   *
   * <code>.basekv.Range range = 5;</code>
   * @return The range.
   */
  com.zachary.bifromq.basekv.proto.Range getRange();
  /**
   * <pre>
   * merger's range at the moment
   * </pre>
   *
   * <code>.basekv.Range range = 5;</code>
   */
  com.zachary.bifromq.basekv.proto.RangeOrBuilder getRangeOrBuilder();
}
